spring:
  main:
    allow-circular-references: true
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/news_db
    username: postgres
    password: postgres
    hikari:
      schema: news_schema
      connection-ini-sql: CREATE SCHEMA IF NOT EXISTS news_schema
      connection-timeout: 10000


springdoc:
  swagger-ui:
    tagsSorter: alpha

